'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class boek_wijzigen

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''frmMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''litAangemeld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAangemeld As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblBevoegd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBevoegd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBoekBestaat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoekBestaat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlWrapper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWrapper As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgCover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCover As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCover As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fuCover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuCover As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblCoverForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoverForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCoverSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoverSize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblISBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISBN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtISBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtISBN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBestaat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestaat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''revISBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revISBN As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvISBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvISBN As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblTitel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTitel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTitel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTitel As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblAuteurs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAuteurs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAuteurA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuteurA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvAuteur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAuteur As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblAuteursFill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAuteursFill As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAuteurB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuteurB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblJaar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJaar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtJaar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJaar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revJaar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revJaar As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblUitgeverij control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUitgeverij As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtUitgeverij control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUitgeverij As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvUitgeverij control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvUitgeverij As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblBladzijden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBladzijden As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBladzijden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBladzijden As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revBladzijden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revBladzijden As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTags As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTags As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFlaptekst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlaptekst As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFlaptekst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFlaptekst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBijwerken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBijwerken As Global.System.Web.UI.WebControls.Button
End Class
